# Five Interesting Pytorch functions
Pytorch is a machine learning library built using python by Facebook AI lab for deep learning projects such as computer vision, natural language processing, etc. 

I will be discussing six pytorch features with example.

- is_tensor
- squeeze / unsqueeze
- dstack / hstack
- generators
- sigmoid

Before we begin, let's install and import PyTorch

In [2]:
# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
!pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |████████████████████████████████| 159.3MB 91kB/s 
     |████████████████████████████████| 11.8MB 30.7MB/s 
     |████████████████████████████████| 7.6MB 3.5MB/s 
  Found existing installation: torch 1.7.0+cu101
    Uninstalling torch-1.7.0+cu101:
      Successfully uninstalled torch-1.7.0+cu101
  Found existing installation: torchvision 0.8.1+cu101
    Uninstalling torchvision-0.8.1+cu101:
      Successfully uninstalled torchvision-0.8.1+cu101


In [3]:
# Import torch and other required modules
import torch

## Function 1 - is_tensor()

is_tensor() aids one to confirm if a variable is a tensor or not. Its basically helps one against typechecking.

In [ ]:
# Example 1:  with 2 by 2 Matrix 
tensor_2_2 = torch.tensor([[6, 8], [12, 4]])
torch.is_tensor(tensor_2_2) #Right way of doing it

True

Example 1 shows we use the method or function on a tensor. We store the tensor in a variable and then, parse the tensor through the is_tensor method, which help us to confirm if its teensor or not.

In [ ]:
# Example 2:  with 3 by 4 Matrix 
tensor_3_4 = torch.tensor([[3,5,8],[4,6,2],[1,1,1],[5,5,5]])
torch.is_tensor(tensor_3_4)

True

Example 2 is similar to the first one but we alter the dimension of the matrix and then try it and it worked.

In [ ]:
# Example 3:  How not use the method 
tensor_2_2.is_tensor() #Wrong way of doing it

AttributeError: ignored

Example 3 shows we can't use the method by using the chaining technique.

**Closing comments:** We have seen how we can use is_tensor() function and also how not use it. Above all, it becomes relevant when one intends to avoid typechecking style because is_tensor() is easy to use.

Let's save our work using Jovian before continuing.

In [ ]:
!pip install jovian --upgrade --quiet

     |████████████████████████████████| 71kB 6.4MB/s 


In [ ]:
import jovian

## Function 2 - Torch.Sigmoid

Torch.Sigmoid aids in generating sigmoids output of an input tensor.

In [ ]:
# Example 1 - Using 4 by 4 tensors
tensor_4_4 = torch.randn(4,4) 
torch.sigmoid(tensor_4_4)

tensor([[0.3066, 0.7273, 0.1178, 0.5707],
        [0.8368, 0.5739, 0.6258, 0.8098],
        [0.6415, 0.2513, 0.6646, 0.6127],
        [0.5038, 0.6232, 0.3273, 0.7124]])

Example 1 shows how one can convert tensor values into sigmoid values. We simply generate a tensor from a random 4 by 4 matrix. And then store it in a variable tensor_4_4, then parse the variable to the method (torch.sigmoid()).

In [ ]:
# Example 2 - working
tensor_2_2a = torch.tensor([[2.0, 3.0], [1.2, 2.4]])
torch.sigmoid(tensor_2_2a)

tensor([[0.8808, 0.9526],
        [0.7685, 0.9168]])

Example 2 shows we can do the same with self generate tensor instead of using randomly generated tensor. Its basically the same with example 1, just that the inputs are generated differently.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)

In [ ]:
tensor_2_3 = torch.tensor([[3, 3], [5, 2], [9,1]])
torch.sigmoid(tensor_2_3)

RuntimeError: ignored

Example 3 shows how torch.sigmoid() function is not sensitive to integers or whole numbers because it assumes its a 'Long integer' 

**Closing comments:** We have learnt how to use torch.sigmoid function to convert tensor values to sigmoid values and also, the datatype that the function is sensitive to. 

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 3 - Squeeze and Unsqueeze

The squeeze and unsqueeze function helps to change the size or shape of a tensor.

In [5]:
# Example 1: Squeezing tensors
x = torch.zeros(3, 1, 5, 2, 4)
print("Orignial size, x: ",x.size())
y = torch.squeeze(x)
print("Squeezed size, y: ",y.size())

x1 = torch.zeros(1, 2, 2, 1, 2)
y0 = torch.squeeze(x1, 0) #0
print("Squeezed, y0: ", y0.size()) 
y1 = torch.squeeze(x1, 1)  #1
print("Squeezed, y1: ", y1.size())
y2 = torch.squeeze(x1, -2)  #-2
print("Squeezed, y2: ", y2.size())

Orignial size, x:  torch.Size([3, 1, 5, 2, 4])
Squeezed size, y:  torch.Size([3, 5, 2, 4])
Squeezed, y0:  torch.Size([2, 2, 1, 2])
Squeezed, y1:  torch.Size([1, 2, 2, 1, 2])
Squeezed, y2:  torch.Size([1, 2, 2, 2])


In example 1, we were able to alter the shape of the tensor, x. x and x1 were the input tensors, after squeezing, the shape have been reduced from 1 by 5 to 1 by 4. However, this is between -2 to 1 in (x, **0**). 

In [6]:
# Example 2: Unsqueezing tensors

x = torch.tensor([4, 2, 3, 4])
print(torch.unsqueeze(x, 0))
print(torch.unsqueeze(x, 1))
print(torch.unsqueeze(x, -2))

tensor([[4, 2, 3, 4]])
tensor([[4],
        [2],
        [3],
        [4]])
tensor([[4, 2, 3, 4]])


Example 2 shows how we can unsqueeze tensors by using the torch.unsqueeze() with the tensors as an input argument.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
x2 = torch.zeros(3)
y4 = torch.squeeze(x2, 2)
print("Squeezed:", y4.size())


IndexError: ignored

Example 3, shows that squeeze.tensor() has a range and any value out of the range cannot be taken.

**Closing comments:** We learnt how to use both the squeeze and unsqueeze pytorch functions.


In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 4 - Dstack and Hstack

Dstack and Hstack is all about how we can concatenate tensors using pytorch.

In [ ]:
# Example 1: dstack example
a = torch.tensor([3, 2, 4])
b = torch.tensor([6, 4, 8])
torch.dstack((a,b))

tensor([[[3, 6],
         [2, 4],
         [4, 8]]])

Example 1 shows how dstack concatenate tensors vertically.

In [ ]:
# Example 2 - working
a = torch.tensor([4, 3, 6])
b = torch.tensor([6, 4, 8])
torch.hstack((a,b))

tensor([4, 3, 6, 6, 4, 8])

Example 2 shows how hstack concatenate tensors horizontally.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
a = torch.tensor([4, 2, 8,9])
b = torch.tensor([5, 5, 7])
print(torch.hstack((a,b)))
print(torch.dstack((a,b)))

tensor([4, 2, 8, 9, 5, 5, 7])


RuntimeError: ignored

Example 3 shows that, different dimension of tensors can be concatenated horizontally but throws error when we intend to concatenate them vertically.

**Closing comments:** We learnt how to use hstack and dstack methods in pytorch and their limitations.

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 5 - Generators

Its a class that creates and generates an object that manage the condition of an algorithm.

In [ ]:
# Example 1: getting the condition of a generator
g_cpu = torch.Generator()
g_cpu.get_state()
#print(g_cuda)

tensor([  1, 209, 156,  ...,   0,   0,   0], dtype=torch.uint8)

Example 1 shows us how a generator can be restored at a specific point in time.

In [ ]:
# Example 2: Initial seed
g_cpu = torch.Generator()
g_cpu.initial_seed()

67280421310721

Example 2 shows us how one can return an initial seed while generating random numbers.

In [ ]:
# Example 3: initial seed
g_cpu = torch.Generator()
g_cpu.initial_seed(2)

TypeError: ignored

In example 3, we learnt how that initial seed doesn't take arguments.

**Closing comments:** We learnt about generator function, what it is and how works, and the limitation or breaking point of the function.

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Conclusion

We were able to cover 5 fascinating functions in pytorch, their strength and weaknesses. By next week, we will dive deeper into pytorch. :)

## Reference Links

- is_tensor: 
   - https://pytorch.org/docs/stable/generated/torch.is_tensor.html#torch.is_tensor

- squeeze / unsqueeze: 
  - https://pytorch.org/docs/stable/generated/torch.unsqueeze.html#torch.unsqueeze
  - https://pytorch.org/docs/stable/generated/torch.squeeze.html#torch.squeeze

- dstack / hstack: 
   - https://pytorch.org/docs/stable/generated/torch.dstack.html#torch.dstack

   - https://pytorch.org/docs/stable/generated/torch.hstack.html#torch.hstack

- generators: 
   - https://pytorch.org/docs/stable/generated/torch.Generator.html#torch.Generator

- sigmoid: 
 - https://pytorch.org/docs/stable/generated/torch.sigmoid.html#torch.sigmoid

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
